package io.aequicor.aikit.cli.commands

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.CliktError
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.arguments.optional
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.option
import io.aequicor.aikit.cli.util.resolveManifestOrFail
import io.aequicor.aikit.engine.api.ManifestResolver
import io.aequicor.aikit.engine.remove.LockNotFoundError
import io.aequicor.aikit.engine.remove.ProjectRemover
import io.aequicor.aikit.engine.remove.RemoveOptions
import io.aequicor.aikit.engine.remove.RemoveReport
import kotlinx.io.files.Path
import kotlinx.io.files.SystemFileSystem

/**
 * Removes AI-Kit-generated files from a project using `.aikit/manifest.lock.json`.
 *
 * Tracked files whose contents you've modified since the last `generate` are kept by default —
 * use `--force` to delete them anyway. With `--keep-manifest` the `.aikit/` directory and the
 * lock file remain in place so you can re-generate later.
 */
class RemoveCommand(
    private val remover: ProjectRemover,
    private val manifestResolver: ManifestResolver,
) : CliktCommand(
    name = "remove",
    help = "Remove files generated by AI-Kit from this project",
) {
    private val manifestArg by argument(
        name = "MANIFEST",
        help = "Path to the manifest file (default: resolved from .aikit/local.properties or .aikit/manifest.json)",
    ).optional()

    private val manifestOpt by option(
        "--manifest",
        help = "Explicit path to the manifest file",
    )
    private val modeOpt by option(
        "--mode",
        help = "Shorthand for --manifest .aikit/manifest.<mode>.json",
    )
    private val dryRun by option("--dry-run", help = "Show what would be deleted without touching the filesystem").flag()
    private val force by option(
        "--force",
        help = "Also delete tracked files that you've modified after generation",
    ).flag()
    private val keepManifest by option(
        "--keep-manifest",
        help = "Keep .aikit/manifest.json and manifest.lock.json in place",
    ).flag()

    override fun run() {
        val resolved = resolveManifestOrFail(
            resolver = manifestResolver,
            positionalArg = manifestArg,
            manifestFlag = manifestOpt,
            modeFlag = modeOpt,
            echo = ::echo,
        )
        val projectRoot = resolveProjectRoot(resolved.manifestPath)

        val report = remover.remove(
            projectRoot,
            RemoveOptions(dryRun = dryRun, force = force, keepManifest = keepManifest),
        ).getOrElse { error ->
            val msg = when (error) {
                is LockNotFoundError -> "Lock file not found at '${error.lockPath}'. " +
                    "Run `kit-setup generate` first, or delete the AI-Kit folders manually."
                else -> error.message ?: "Removal failed"
            }
            throw CliktError(msg, statusCode = 1)
        }

        printReport(report)
    }

    private fun resolveProjectRoot(manifestPath: String): String {
        val p = Path(manifestPath)
        val parentParent = p.parent?.parent
        val resolved = parentParent ?: Path(".")
        return runCatching { SystemFileSystem.resolve(resolved) }.getOrDefault(resolved).toString()
    }

    private fun printReport(report: RemoveReport) {
        val prefix = if (report.dryRun) "[dry-run] " else ""
        if (report.deleted.isNotEmpty()) {
            echo("${prefix}Deleted (${report.deleted.size}):")
            report.deleted.forEach { echo("  - $it") }
        }
        if (report.skippedDrift.isNotEmpty()) {
            echo("Kept — modified by you after generation (use --force to remove):")
            report.skippedDrift.forEach { echo("  ! $it") }
        }
        if (report.missing.isNotEmpty()) {
            echo("Already gone: ${report.missing.size} file(s)")
        }
        if (report.manifestRemoved) {
            echo("${prefix}Removed .aikit/manifest.json and manifest.lock.json")
        }
        echo(if (report.dryRun) "Dry run complete." else "Done.")
    }
}
