import java.io.File

plugins {
    id("ai-kit.kotlin-module")
    id("ai-kit.detekt")
}

// ---------------------------------------------------------------------------
// Embedded-bundle codegen
// ---------------------------------------------------------------------------

val bundlesRootDir: File = rootProject.file("bundles")
val generatedSrcDir = layout.buildDirectory.dir("generated/embeddedBundles/commonMain/kotlin")

val generateEmbeddedBundles by tasks.registering {
    group = "build"
    description = "Generate EmbeddedBundleData.kt by baking bundles/ into source byte arrays"
    inputs.dir(bundlesRootDir)
    outputs.dir(generatedSrcDir)

    doLast {
        val outFile = generatedSrcDir.get().asFile
            .resolve("io/aequicor/aikit/io/embedded/EmbeddedBundleData.kt")
        outFile.parentFile.mkdirs()
        outFile.writeText(buildEmbeddedBundleSource(bundlesRootDir))
    }
}

kotlin {
    sourceSets {
        commonMain {
            kotlin.srcDir(generatedSrcDir)
            dependencies {
                implementation(libs.kotlinx.io.core)
            }
        }
    }
    targets.all {
        compilations.all {
            compileTaskProvider.configure { dependsOn(generateEmbeddedBundles) }
        }
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeTest>().configureEach {
    workingDir = projectDir.absolutePath
}

// ---------------------------------------------------------------------------
// Code generator (runs on Gradle JVM)
// ---------------------------------------------------------------------------

fun buildEmbeddedBundleSource(bundlesRoot: File): String {
    data class BundleMeta(val name: String, val version: String, val description: String?)

    val bundles = mutableListOf<Pair<BundleMeta, Map<String, ByteArray>>>()

    bundlesRoot.listFiles()
        ?.filter { it.isDirectory }
        ?.sortedBy { it.name }
        ?.forEach { bundleDir ->
            val manifestFile = File(bundleDir, "bundle.json")
            if (!manifestFile.exists()) return@forEach

            val manifestText = manifestFile.readText()
            val name = extractJsonString(manifestText, "name") ?: return@forEach
            val version = extractJsonString(manifestText, "version") ?: return@forEach
            val description = extractJsonString(manifestText, "description")

            val files = mutableMapOf<String, ByteArray>()
            bundleDir.walkTopDown()
                .filter { it.isFile }
                .sortedBy { it.relativeTo(bundleDir).path }
                .forEach { file ->
                    val relative = file.relativeTo(bundleDir).path.replace(File.separatorChar, '/')
                    files[relative] = file.readBytes()
                }

            bundles += BundleMeta(name, version, description) to files
        }

    return buildString {
        appendLine("// Generated by :modules:io:generateEmbeddedBundles — do not edit.")
        appendLine("package io.aequicor.aikit.io.embedded")
        appendLine()
        appendLine("// Catalog is public — accessed from :modules:engine.")
        appendLine("data class EmbeddedBundleMeta(")
        appendLine("    val name: String,")
        appendLine("    val version: String,")
        appendLine("    val description: String?,")
        appendLine(")")
        appendLine()
        appendLine("val embeddedBundleCatalog: List<EmbeddedBundleMeta> = listOf(")
        for ((meta, _) in bundles) {
            val desc = meta.description?.let { "\"${it.kotlinEscape()}\"" } ?: "null"
            appendLine("    EmbeddedBundleMeta(\"${meta.name.kotlinEscape()}\", \"${meta.version.kotlinEscape()}\", $desc),")
        }
        appendLine(")")
        appendLine()
        appendLine("internal val embeddedBundleFiles: Map<String, Map<String, ByteArray>> = mapOf(")
        for ((meta, files) in bundles) {
            appendLine("    \"${meta.name.kotlinEscape()}\" to mapOf(")
            for ((path, bytes) in files) {
                append("        \"${path.kotlinEscape()}\" to byteArrayOf(")
                append(bytes.joinToString(",") { it.toString() })
                appendLine("),")
            }
            appendLine("    ),")
        }
        appendLine(")")
    }
}

fun extractJsonString(json: String, key: String): String? {
    val pattern = Regex(""""${Regex.escape(key)}"\s*:\s*"((?:[^"\\]|\\.)*)"""")
    return pattern.find(json)?.groupValues?.get(1)
        ?.replace("\\\"", "\"")
        ?.replace("\\\\", "\\")
        ?.replace("\\/", "/")
}

fun String.kotlinEscape(): String = this
    .replace("\\", "\\\\")
    .replace("\"", "\\\"")
    .replace("\n", "\\n")
    .replace("\r", "\\r")
    .replace("\t", "\\t")
    .replace("\$", "\\\$")
